# Generated by Django 5.0.6 on 2024-06-11 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                (
                    "rodzaj",
                    models.CharField(
                        choices=[("Jadalne", "Jadalne"), ("Niejadalne", "Niejadalne")],
                        default="Jadalne",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grzyb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                ("opis", models.TextField()),
                (
                    "zdjecie",
                    models.ImageField(upload_to="images", verbose_name="Zdjęcie"),
                ),
                ("utworzono", models.DateTimeField(auto_now_add=True)),
                (
                    "kategoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grzyby",
                        to="grzyby.kategoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zdjecie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zdjecie",
                    models.ImageField(upload_to="grzyby", verbose_name="Zdjęcie"),
                ),
                (
                    "grzyb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zdjecia",
                        to="grzyby.grzyb",
                    ),
                ),
            ],
        ),
    ]
