# Generated by Django 5.0.6 on 2024-06-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grzyby", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kategoria",
            name="rodzaj",
        ),
        migrations.AddField(
            model_name="kategoria",
            name="jadalne",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="kategoria",
            name="opis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
