# Generated by Django 5.0.6 on 2024-06-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grzyby", "0002_remove_kategoria_rodzaj_kategoria_jadalne_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grzyb",
            name="zdjecie",
        ),
        migrations.RemoveField(
            model_name="zdjecie",
            name="grzyb",
        ),
        migrations.AddField(
            model_name="grzyb",
            name="zdjecia",
            field=models.ManyToManyField(related_name="grzyby", to="grzyby.zdjecie"),
        ),
        migrations.RemoveField(
            model_name="grzyb",
            name="kategoria",
        ),
        migrations.AddField(
            model_name="grzyb",
            name="kategoria",
            field=models.ManyToManyField(related_name="grzyby", to="grzyby.kategoria"),
        ),
    ]
